version: '3.7'
services:
  api-webservice:
    container_name: api-webservice
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_NAME: api-webservice
      APP_PORT: 4000
      
      #postgres params
      DB_PORT: 5432
      DB_HOST: postgres
      DB: app_data
      DB_USER: user
      DB_PASSWORD: password

      #prisma settings
      PG_URL: postgresql://user:password@postgres:5432/app_data?schema=public
    volumes:
      - ./src/client/scss:/usr/src/app/src/client/scss/
      - ./src/client/views/:/usr/src/app/dist/src/client/views/
    ports:
      - "127.0.0.1:4000:4000"
    networks:
      - app_network
    depends_on:
      - postgres
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/sql/:/docker-entrypoint-initdb.d
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=app_data
    networks:
      - app_network
volumes:
  pgdata:
networks:
  app_network:
    driver: bridge